chore: update for testing Bazel 7 as primary and Bazel 6 as secondary

diff --git a/.github/workflows/release_ruleset.yaml b/.github/workflows/release_ruleset.yaml
--- a/.github/workflows/release_ruleset.yaml
+++ b/.github/workflows/release_ruleset.yaml
@@ -1,10 +1,14 @@
-# Reusable workflow that can be referenced by repositories in their .github/workflows/release.yaml.
+# Reusable workflow that can be referenced by repositories in their `.github/workflows/release.yaml`.
 # See example usage in https://github.com/bazel-contrib/rules-template/blob/main/.github/workflows/release.yaml
 #
-# This assumes the repo calling the workflow has at least these files:
-# - .github/workflows/release_prep.sh
-# - .github/workflows/ci.bazelrc
-# - .bazelrc
+# By default this workflows calls `.github/workflows/release_prep.sh` as the command to prepare
+# the release. This can be customized with the `release_prep_command` attribute. Release notes are
+# expected to be outputted to stdout from the release prep command.
+#
+# This workflow automatically configures the disk_cache and repository_cache directories to
+# `~/.cache/bazel-disk-cache` and `~/.cache/bazel-repo-cache` respectively. It also sets the XDG_CACHE_HOME
+# env to `~/.cache/xdg-cache-home` which is used by bazelisk when downloading Bazel. GitHub Actions caching
+# is configured for these directories. Caching may be disabled by setting `mount_bazel_caches` to false.
 
 on:
   # Make this workflow reusable, see
@@ -17,6 +21,24 @@ on:
           Newline-delimited globs of paths to assets to upload for release.
           See https://github.com/softprops/action-gh-release#inputs
         type: string
+      release_prep_command:
+        default: .github/workflows/release_prep.sh
+        description: |
+          Command to run to prepare the release and generate release notes.
+          Release notes are expected to be outputted to stdout.
+        type: string
+      bazel_test_command:
+        default: "bazel test //..."
+        description: |
+          Bazel test command that may be overridden to set custom flags and targets.
+          The --disk_cache=~/.cache/bazel-disk-cache --repository_cache=~/.cache/bazel-repository-cache flags are
+          automatically appended to the command.
+        type: string
+      mount_bazel_caches:
+        default: true
+        description: |
+          Additional startup flags to pass to the 'bazel test //...' invocation
+        type: boolean
       prerelease:
         default: true
         description: Indicator of whether or not is a prerelease
@@ -27,21 +49,32 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       - name: Mount bazel caches
         uses: actions/cache@v3
+        if: ${{ inputs.mount_bazel_caches }}
         with:
           path: |
-            ~/.cache/bazel
-          key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE') }}
-          restore-keys: bazel-cache-
-      - name: bazel test //...
+            ~/.cache/bazel-disk-cache
+            ~/.cache/bazel-repository-cache
+            ~/.cache/xdg-cache-home
+          key: bazel-cache-release-${{ hashFiles('.bazelrc', '.bazelversion', '.bazeliskrc', '**/BUILD', '**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', 'WORKSPACE.bazel', 'WORKSPACE.bzlmod', 'MODULE.bazel', 'MODULE.bazel.lock') }}
+          restore-keys: bazel-cache-release-
+      - name: Test
+        run: ${{ inputs.bazel_test_command }} --disk_cache=~/.cache/bazel-disk-cache --repository_cache=~/.cache/bazel-repository-cache
         env:
-          # Bazelisk will download bazel to here.
-          XDG_CACHE_HOME: ~/.cache/bazel-repo
-        run: bazel --bazelrc=.github/workflows/ci.bazelrc --bazelrc=.bazelrc test //...
-      - name: Prepare release notes and artifacts
-        run: .github/workflows/release_prep.sh ${{ env.GITHUB_REF_NAME }} > release_notes.txt
+          # Bazelisk will download bazel to here
+          XDG_CACHE_HOME: ~/.cache/xdg-cache-home
+      - name: Build release artifacts and prepare release notes
+        run: |
+          if [ ! -f "${{ inputs.release_prep_command }}" ]; then
+            echo "ERROR: create a ${{ inputs.release_prep_command }} release prep script or configure a different release prep command with the release_prep_command attribute"
+            exit 1
+          fi
+          ${{ inputs.release_prep_command }} ${{ env.GITHUB_REF_NAME }} > release_notes.txt
+        env:
+          # Bazelisk will download bazel to here
+          XDG_CACHE_HOME: ~/.cache/xdg-cache-home
       - name: Release
         uses: softprops/action-gh-release@v1
         with:
